[package]
name = "NGmergers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ngmerge-sys = {path="ngmerge-sys"}
lazy_static = "*"
